print(" 'My Last Duchess' by Robert Browning(1812-1889)")
print("That’s my last Duchess painted on the wall,")
print("Looking as if she were alive. I call")
print("piece a wonder, now; Fra Pandolf’s hands")
print("Worked busily a day, and there she stands.")
print("Will’t please you sit and look at her? I said")
print(" 'Fra Pandolf' by design, for never read")
print("Strangers like you that pictured countenance,")
print("The depth and passion of its earnest glance,")
print("But to myself they turned (since none puts by")
print("The curtain I have drawn for you, but I")
print("And seemed as they would ask me, if they durst,")
print("How such a glance came there; so, not the first")
print("Are you to turn and ask thus. Sir, ’twas not")
print("Her husband’s presence only, called that spot")
print("Of joy into the Duchess’ cheek; perhaps")
print("Fra Pandolf chanced to say, “Her mantle laps")
print("Over my lady’s wrist too much,” or “Paint")
print("Must never hope to reproduce the faint")
print("Half-flush that dies along her throat.” Such stuff")
print("Was courtesy, she thought, and cause enough")
print("For calling up that spot of joy. She had")
print("A heart—how shall I say?— too soon made glad,")
print("Too easily impressed; she liked whate’er")
print("She looked on, and her looks went everywhere.")
print("Sir, ’twas all one! My favour at her breast,")
print("The dropping of the daylight in the West,")
print("The bough of cherries some officious fool")
print("Broke in the orchard for her, the white mule")
print("She rode with round the terrace—all and each")
print("Would draw from her alike the approving speech,")
print("Or blush, at least. She thanked men—good! but thanked")
print("Somehow—I know not how—as if she ranked")
print("My gift of a nine-hundred-years-old name")
print("With anybody’s gift. Who’d stoop to blame")
print("This sort of trifling? Even had you skill")
print("In speech—which I have not—to make your will")
print("Quite clear to such an one, and say, “Just this")
print("Or that in you disgusts me; here you miss,")
print("Or there exceed the mark”—and if she let")
print("Herself be lessoned so, nor plainly set")
print("Her wits to yours, forsooth, and made excuse—")
print("E’en then would be some stooping; and I choose")
print("Never to stoop. Oh, sir, she smiled, no doubt,")
print("Whene’er I passed her; but who passed without")
print("Much the same smile? This grew; I gave commands;")
print("Then all smiles stopped together. There she stands")
print("As if alive. Will’t please you rise? We’ll meet")
print("The company below, then. I repeat,")
print("The Count your master’s known munificence")
print("Is ample warrant that no just pretense")
print("Of mine for dowry will be disallowed;")
print("Though his fair daughter’s self, as I avowed")
print("At starting, is my object. Nay, we’ll go")
print("Together down, sir. Notice Neptune, though,")
print("Taming a sea-horse, thought a rarity,")
print("Which Claus of Innsbruck cast in bronze for me!")