print("Question 3: Please read the poem provided below, 'Elegy for Jane' by Theodore Roethke.")
print("Then, in a well written essay, describe the speaker's attitude toward his former student, Jane.")
print("         I remember the neckcurls, limp and damp as tendrils;")
print("         And her quick look, a sidelong pickerel smile;")
print("         And how, once startled into talk, the light syllables leaped for her,")
print("         And she balanced in the delight of her thought,")
print("5        A wren, happy, tail into the wind,")
print("         Her song trembling the twigs and small branches.")
print("         The shade sang with her;")
print("         The leaves, their whispers turned to kissing,")
print("         And the mould sang in the bleached valleys under the rose.")
print("10       Oh, when she was sad, she cast herself down into such a pure depth,")
print("         Even a father could not find her:")
print("         Scraping her cheek against the straw,")
print("         Stirring the clearest water.")
print("         My sparrow, you are not here,")
print("15       Waiting like a fern, making a spiney shadow.")
print("         The sides of wet stones cannot console me,")
print("         Nor the moss, wound with the last light.")
print("         If only I could nudge you from this sleep,")
print("         My maimed darling, my skittery pigeon.")
print("20       Over this damp grave I speak the words of my love:")
print("         I, with no rights in this matter,")
print("         Neither father nor lover.")
