print("         Please read the provided poem, 'Elegy for Jane' by Theodore Roethke.")
print("         Then, in a well written essay, describe the speaker's attitude toward his former student, Jane.")
print("         I remember the neckcurls, limp and damp as tendrils;")
print("         And her quick look, a sidelong pickerel smile;")
print("         And how, once startled into talk, the light syllables leaped for her,")
print("         And she balanced in the delight of her thought,")
print("5        A wren, happy, tail into the wind,")
print("         Her song trembling the twigs and small branches.")
print("         The shade sang with her;")
print("         The leaves, their whispers turned to kissing,")