print("Question 2: Read the following exert from 'Rock Eaters' written by Brenda Peynado.")
print("Then, in a well written essay, analyze how Peynado uses literary elements and techniques to convey the")
print("narrator's complex experience of this return home.")



print("  We were the first generation to leave our island       us. 'We remember,' we said, recoiling at how little")
print("country. We were the ones who developed a distinct       the place fit us anymore. Those first nights we slept in")
print("float to our walk on the dya we came of age. Soon       our old beds, our feet hanging over the edges, the")
print("enough, we were hovering inches above the ground,       noises of the city and the country crowing and")
print("then somersaulting with the clouds, finally       honking us awake, music from radios and guitars,")
print("discovering we could fly as far as we'd ever wanted.       celebrations we'd not been invited to.")
print("And so we left. Decades later, we brought our        We dragged our children along to knock on the")
print("children back to see our home country. That year, we        doors of old friends and siblings, the ones who never")
print("all decided we were finally ready to return.         developed the ability to fly. They eventually,")
print("  We jackknifed through the clouds and dodged large      reluctantly, opened their doors. At first we sat stiffly")
print("birds. We held our children tightly; they had not yet        on couches and inquired after their health and others")
print("learned to fly. Behind us trailed roped-together lines       we once knew. Then we got them to laugh with us")
print("of suitcases packed with gifts from abroad. We           about the time we pulled the nuns' skirts or put gum")
print("wondered who would remember us.          in the kink of a rival's hair, when we caught baby")
print("  Our parents, those who were still alive, came out to          chicks in the village and raised them, or cracked open")
print("greet us, hands on the brows like visors. Some were          almonds on the malecon. Then their children came")
print("expecting us. Others were surprised, terrified at the        shyly out of their rooms and took ours by the hand.")
print("spectacle of millions of their prodigals blotting the        We smiled when we saw them climbing trees together")
print("sky with our billowing skirts, our shirts starched for       in the patios, their children showing ours how to eat")
print("the arrival. We touched down on our parents'         cajuilitos soliman and acerolas from the branch.")
print("driveways, skidding to rough landings at their feet,         We introduced our children to everyone we use to")
print("denting cars, squashing flowers, rattling windows.           know: at colmados, by the side of the road, at the")
print("  Our friends and siblings, the ones we'd left           baseball fields, at country clubs we had to beg to be")
print("behind, kept their doors locked. They peered through        let back into. We showed them the granite striated through the")
print("window blinds at the flattened flowerbeds, the           trees in the parks, blooms of coral red spilling in the")
print("suitcases that had burst and strewn packages all over        dirt. We showed them the granite striated through the")
print("the yards and streets, our youngest children squealing           rock faces of mountains, the glimmering pebbles")
print("now that they'd been released, the peace we'd broken         under waterfalls, the red dust that stained the seats of")
print("by returning. They didn't trust us, not after our        their best clothes. We walked past the stray dogs and")
print("betrayal decades ago, the whiff of money we'd earned         growled and whined; the most ancient among them")
print("or lost in other countries like a suspect stench. Our        remembered us, wagging their tails when they saw us")
print("parents hugged their grandchildren and brought them          and running to sniff our offspring. We dunked our")
print("inside to houses with no electricity, candles wavering           children into the rivers we'd once swum. We dug")
print("like we were in a seance. 'More brownouts,' they told(go to 'us')            through the banks for the arrowheads that belonged to")
print("the Tainos, who'd been erased after the Spanish came,")
print("their remnants lost in the mud.")
print("     Lost, the children whispered in awe and fear")
print("turning the black, glinting points in their palms,")
print("testing the hardness of flint between their teeth. Back")
print("in our foreign homes, we had never talked to them of")
print("history.")
print("     We remembered we'd been happy. 'We loved this land,' we said. We forgot why we ever left.")
